// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/MeetMeshHostPanel.tsx": () => import("../components/mockups/MeetMeshHostPanel.tsx"),
  "./components/mockups/MeetMeshJoinProfile.tsx": () => import("../components/mockups/MeetMeshJoinProfile.tsx"),
  "./components/mockups/MeetMeshLanding.tsx": () => import("../components/mockups/MeetMeshLanding.tsx"),
  "./components/mockups/MeetMeshMeetingRoom.tsx": () => import("../components/mockups/MeetMeshMeetingRoom.tsx"),
  "./components/mockups/MeetMeshPresentation.tsx": () => import("../components/mockups/MeetMeshPresentation.tsx"),
  "./components/mockups/MeetMeshWaitingRoom.tsx": () => import("../components/mockups/MeetMeshWaitingRoom.tsx")
};
